DROP DATABASE HKLProject
/* TABLE LIST:  ACCOUNT, CUSTOMER, ADMIN, ORDER, PAY METHOD, ORDER DETAIL, PRODUCT, CATEGORY, SUPPLIER */
CREATE DATABASE HKLProject
GO
USE HKLProject
GO
CREATE TABLE Account/* CONSTRAINT FOR ID + PASS *//* Admin or Customer*/
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Roll VARCHAR(10) NOT NULL, 
	UserName VARCHAR(15) NOT NULL,
	UserPassword VARCHAR(20) NOT NULL
)
GO
CREATE TABLE Customer/*CONSTRAINT GENDER, BIRTHDAY, EMAIL , PHONE, FBLINK*/
(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	Gender BIT NULL,
	BirthDay DATE NULL,
	Email VARCHAR(50) NULL, 
	PhoneNumber CHAR(12) NOT NULL,
	FullAddress NVARCHAR(50) NULL,
	FacebookLink VARCHAR(50) NULL
)
GO
CREATE TABLE AdminUser
(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	PhoneNumber CHAR(12) NOT NULL
)
GO
CREATE TABLE Orders
(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	CreateDay DATE NOT NULL,
	IdCustomer INT NOT NULL,
	IdPayMethod INT NOT NULL
)
GO
CREATE TABLE PayMethod
(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	MethodName NVARCHAR(20) NOT NULL,
	Visible BIT NOT NULL
)
GO
CREATE TABLE OrderDetail /*SO LUONG, THANH TIEN, SIZE , GIA*/
(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	IdOrder INT NOT NULL,
	IdProduct INT NOT NULL,
	Quantity INT NOT NULL,
	Price MONEY NOT NULL,
	TotalPrice MONEY NOT NULL,
	Size CHAR(15) NULL
)
GO
CREATE TABLE Product
(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	IdSupplier INT NOT NULL,
	IdCategory INT NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Images NVARCHAR(MAX) NULL,
	Material NVARCHAR(50) NOT NULL,
	Descriptions NTEXT NULL,
	Price MONEY NOT NULL,
	Quantity INT NOT NULL,
	Active BIT NOT NULL 
)
GO
CREATE TABLE Category
(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	CategoryName NVARCHAR(30) NOT NULL,
	CategoryDescription NVARCHAR(50) NULL
)
GO
CREATE TABLE Supplier
(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	CompanyName NVARCHAR(50) NOT NULL,
	CompanyAddress NVARCHAR(50) NOT NULL,
	Email VARCHAR(30) NULL,
	PhoneNumber VARCHAR(15) NULL
)

ALTER TABLE Account
ADD CONSTRAINT FK_Cus_Acc
FOREIGN KEY (Id) REFERENCES Customer(Id)
GO
ALTER TABLE Account
ADD CONSTRAINT FK_Admin_Acc
FOREIGN KEY (Id) REFERENCES AdminUser(Id)
GO
ALTER TABLE Orders
ADD CONSTRAINT FK_Cus_Orders
FOREIGN KEY (IdCustomer) REFERENCES Customer(Id)
GO
ALTER TABLE Orders
ADD CONSTRAINT FK_PayMethod_Orders
FOREIGN KEY (IdPayMethod) REFERENCES PayMethod(Id)
GO
ALTER TABLE OrderDetail
ADD CONSTRAINT FK_Orders_OrderDetail
FOREIGN KEY (IdOrder) REFERENCES Orders(Id)
GO
ALTER TABLE OrderDetail
ADD CONSTRAINT FK_Product_OrderDetail
FOREIGN KEY (IdProduct) REFERENCES Product(Id)
GO
ALTER TABLE Product
ADD CONSTRAINT FK_Category_Product
FOREIGN KEY (IdCategory) REFERENCES Category(Id)
GO
ALTER TABLE Product
ADD CONSTRAINT FK_Supplier_Product
FOREIGN KEY (IdSupplier) REFERENCES Supplier(Id)



--ALTER TABLE Product
--drop constraint FK_Category_Product
--SELECT * FROM Customer